<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="28" errors="0" failures="5" skip="0"><testcase classname="accounts.test.tests.SignUpTests" name="test_contains_form" time="0.041"></testcase><testcase classname="accounts.test.tests.SignUpTests" name="test_csrf" time="0.005"></testcase><testcase classname="accounts.test.tests.SignUpTests" name="test_signup_status_code" time="0.005"></testcase><testcase classname="accounts.test.tests.SignUpTests" name="test_signup_url_resolves_signup_view" time="0.005"></testcase><testcase classname="accounts.test.tests.SuccesfulSignupTest" name="test_UserCreation" time="0.095"></testcase><testcase classname="accounts.test.tests.SuccesfulSignupTest" name="test_redirection" time="0.097"></testcase><testcase classname="accounts.test.tests.SuccesfulSignupTest" name="test_user_authentication" time="0.095"></testcase><testcase classname="test_mail_password_reset.PasswordResetMailTests" name="test_email_body" time="0.102"></testcase><testcase classname="test_mail_password_reset.PasswordResetMailTests" name="test_email_subject" time="0.091"></testcase><testcase classname="test_mail_password_reset.PasswordResetMailTests" name="test_email_to" time="0.091"></testcase><testcase classname="test_view_password_reset.InvalidPasswordResetTests" name="test_no_reset_email_sent" time="0.002"></testcase><testcase classname="test_view_password_reset.InvalidPasswordResetTests" name="test_redirection" time="0.004"></testcase><testcase classname="test_view_password_reset.PasswordResetTests" name="test_contains_form" time="0.003"></testcase><testcase classname="test_view_password_reset.PasswordResetTests" name="test_csrf" time="0.003"></testcase><testcase classname="test_view_password_reset.PasswordResetTests" name="test_form_inputs" time="0.003"></testcase><testcase classname="test_view_password_reset.PasswordResetTests" name="test_status_code" time="0.003"></testcase><testcase classname="test_view_password_reset.PasswordResetTests" name="test_view_function" time="0.003"></testcase><testcase classname="test_view_password_reset.SuccessfulPasswordResetTests" name="test_redirection" time="0.092"></testcase><testcase classname="test_view_password_reset.SuccessfulPasswordResetTests" name="test_send_password_reset_email" time="0.091"></testcase><testcase classname="boards.tests.BoardTopicsTest" name="test_board_topic_succes_code" time="0.003"></testcase><testcase classname="boards.tests.BoardTopicsTest" name="test_board_topic_url_code" time="0.000"></testcase><testcase classname="boards.tests.HomeTest" name="home_url_test_code" time="0.006"><failure type="builtins.AssertionError" message="&lt;function BoardListView at 0x7efe7eab5488&gt; != &lt;function home at 0x7efe7eab5378&gt;"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/admin/PracticePrograms/BoardProject/BoardProject/boards/tests.py", line 20, in home_url_test_code
    self.assertEquals(view.func, home)
  File "/usr/lib/python3.7/unittest/case.py", line 1338, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: <function BoardListView at 0x7efe7eab5488> != <function home at 0x7efe7eab5378>
]]></failure></testcase><testcase classname="boards.tests.HomeTest" name="test_home_view_contains_link_to_topics_page" time="0.007"></testcase><testcase classname="boards.tests.HomeTest" name="test_home_view_status_code" time="0.004"></testcase><testcase classname="boards.tests.NewTopicTests" name="test_csrf" time="0.089"><failure type="builtins.AssertionError" message="302 != 200 : Couldn't retrieve content: Response code was 302 (expected 200)"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/admin/PracticePrograms/BoardProject/BoardProject/boards/tests.py", line 54, in test_csrf
    self.assertContains(response, 'csrfmiddlewaretoken')
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/test/testcases.py", line 361, in assertContains
    response, text, status_code, msg_prefix, html)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/test/testcases.py", line 333, in _assert_contains
    " (expected %d)" % (response.status_code, status_code)
  File "/usr/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 302 != 200 : Couldn't retrieve content: Response code was 302 (expected 200)
]]></failure></testcase><testcase classname="boards.tests.NewTopicTests" name="test_new_topic_invalid_post_data" time="0.090"><failure type="builtins.AssertionError" message="302 != 200"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/admin/PracticePrograms/BoardProject/BoardProject/boards/tests.py", line 73, in test_new_topic_invalid_post_data
    self.assertEquals(response.status_code, 200)
  File "/usr/lib/python3.7/unittest/case.py", line 1338, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 302 != 200
]]></failure></testcase><testcase classname="boards.tests.NewTopicTests" name="test_new_topic_invalid_post_data_empty_fields" time="0.089"><failure type="builtins.AssertionError" message="302 != 200"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/admin/PracticePrograms/BoardProject/BoardProject/boards/tests.py", line 86, in test_new_topic_invalid_post_data_empty_fields
    self.assertEquals(response.status_code, 200)
  File "/usr/lib/python3.7/unittest/case.py", line 1338, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 302 != 200
]]></failure></testcase><testcase classname="boards.tests.NewTopicTests" name="test_new_topic_valid_post_data" time="0.090"><failure type="builtins.AssertionError" message="False is not true"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/admin/PracticePrograms/BoardProject/BoardProject/boards/tests.py", line 63, in test_new_topic_valid_post_data
    self.assertTrue(Topic.objects.exists())
  File "/usr/lib/python3.7/unittest/case.py", line 692, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
]]></failure></testcase></testsuite>